### ISSUE TITLE
Pythonコード読み取り機能

### ISSUE THREAD

**Issue by k-kageyama** [NCVC-CAM/Scriptorium#2]
439～441行目にPythonファイル読み取り機能を追加する必要がある
元々はPerlファイルを読み取る機能。
443～448行目の内容がどこまで移植できるか確認する。

https://github.com/NCVC-CAM/Scriptorium/blob/52f344f40441d38bd7b66f89a1746c029a66bfbe/Scriptorium/ScriptoriumDlg.cpp#L438-L454

**Comment by K-Magara** [comment]
何か難しく考えすぎてませんか？ｗｗｗ
拡張子によって実行するプログラムを切り替えるだけでしょ．
上の if 文は冗長な書き方を予感させます．

```
CString strEXE;   // 実行するプログラム名
if ( .pl の場合 ) {
  strEXE = "perl"
}
else if ( .py の場合 ) {
  strEXE = "python"
}

if ( strEXE.IsEmpty() ) {
  AfxMessageBox("perl か pythonで～")
}
else {
  tmpStr = strEXE + "\"" + m_strScript + "\"" ...以下省略
  if ( CreateProcess( ... 以下省略
    ... 以下省略
}
```

がんばって！

**Comment by k-kageyama** [comment]
ありがとうございます
IsEmpty()　関数の存在初めて知りました　とても良いですね…これ
